import{a as v,S,i as $}from"./assets/vendor-5b76a5ec.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const P="42558168-62173c93aab0d4cbf34bb4fab",q="https://pixabay.com/api/";async function f(t,o){try{let r=await v.get(`${q}?key=${P}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${o}`);if(!r.data.hits)throw new Error("Network response was not ok");return r.data}catch{}}const E="/goit-js-hw-12/assets/error-icon-4ed38f6a.png",I="/goit-js-hw-12/assets/caution-icon-57f96af6.png",h=document.querySelector(".form"),M=document.querySelector(".search-input"),l=document.querySelector(".gallery"),c=document.querySelector(".load-more-button"),u=document.querySelector(".loader"),m=new S(".gallery a",{captionsData:"alt",captionDelay:150,captionsPosition:"bottom"});let d=null,g=1;h.addEventListener("submit",N);c.addEventListener("click",O);async function N(t){t.preventDefault(),T();try{const r=(await f(d,1)).hits;r.length===0?n():(y(r,l),m.refresh())}catch{n()}finally{p()}}async function O(){C();try{const o=(await f(d,g)).hits;o.length===0?n(!0):(y(o,l),m.refresh())}catch{n()}finally{p()}}function T(){l.innerHTML="",c.classList.add("is-hidden"),u.classList.remove("is-hidden"),d=M.value}function n(t=!1){l.innerHTML="";const o=t?"Were sorry, but you've reached the end of search results.":"Sorry, there are no images matching your search query. Please try again!",r=t?I:E;$.error({message:o,position:"topRight",timeout:5e3,progressBar:!0,close:!0,iconUrl:r,messageColor:t?"#000":"#fafafb",iconColor:t?"#000":"#fafafb",backgroundColor:t?"#90C2DE":"#FF544B"})}function C(){c.classList.add("is-hidden"),u.classList.remove("is-hidden"),g++}function p(){u.classList.add("is-hidden"),c.classList.remove("is-hidden"),h.reset()}function y(t,o){const r=t.map(({webformatURL:i,largeImageURL:e,tags:s,likes:a,views:L,comments:b,downloads:w})=>`<li class="gallery-item">
          <a class="gallery-link" href="${e}">
            <img class="gallery-image" src="${i}" alt="${s}" />
          </a>

          <ul class="gallery-info-list">
            <li class="gallery-info-list-item"><h4>Likes</h4><p>${a}</p></li>
            <li class="gallery-info-list-item"><h4>Views</h4><p>${L}</p></li>
            <li class="gallery-info-list-item"><h4>Comments</h4><p>${b}</p></li>
            <li class="gallery-info-list-item"><h4>Downloads</h4><p>${w}</p></li>
          </ul>
        </li>`).join("");o.insertAdjacentHTML("beforeend",r)}
//# sourceMappingURL=commonHelpers.js.map
